In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.special import comb
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import (KFold,RepeatedKFold,LeaveOneOut,
                                     LeavePOut,StratifiedKFold,cross_validate,train_test_split)

In [5]:
x_breast,y_breast=load_breast_cancer(return_X_y=True)
x=pd.DataFrame(x_breast)
y=pd.Series(y_breast).map({0:1,1:0})
x.head()

0      1       2       3        4        5       6        7       8   \
0  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.3001  0.14710  0.2419   
1  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.0869  0.07017  0.1812   
2  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.1974  0.12790  0.2069   
3  11.42  20.38   77.58   386.1  0.14250  0.28390  0.2414  0.10520  0.2597   
4  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.1980  0.10430  0.1809   

        9   ...     20     21      22      23      24      25      26      27  \
0  0.07871  ...  25.38  17.33  184.60  2019.0  0.1622  0.6656  0.7119  0.2654   
1  0.05667  ...  24.99  23.41  158.80  1956.0  0.1238  0.1866  0.2416  0.1860   
2  0.05999  ...  23.57  25.53  152.50  1709.0  0.1444  0.4245  0.4504  0.2430   
3  0.09744  ...  14.91  26.50   98.87   567.7  0.2098  0.8663  0.6869  0.2575   
4  0.05883  ...  22.54  16.67  152.20  1575.0  0.1374  0.2050  0.4000  0.1625   

       28       29  
0  0.4601  0.11890  
1  0.2750  0.08902  
2  0.3613  0.08758  
3  0.6638  0.17300  
4  0.2364  0.07678  

[5 rows x 30 columns]

In [6]:
#Peretage of the  benign and the malign tumour
y.value_counts()/len(y)

0    0.627417
1    0.372583
dtype: float64

In [8]:
#Split the dataset into the train test split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)
print(x_train.shape)
print(x_test.shape)

(398, 30)
(171, 30)


# K-FOld cross validation

In [11]:
#Logistics Regression
logit=LogisticRegression(penalty='l2',C=10,solver='liblinear',random_state=4,max_iter=10000)
#K-FGold ccross validation
kf=KFold(n_splits=5,shuffle=True,random_state=4)
clf=cross_validate(logit,x_train,y_train,scoring='accuracy',return_train_score=True,cv=kf,)
clf['test_score']

array([0.925     , 0.95      , 0.9625    , 0.96202532, 0.94936709])

In [12]:
clf['train_score']

array([0.97169811, 0.96540881, 0.96855346, 0.96238245, 0.97178683])

In [13]:
print('mean train set accuracy:',np.mean(clf['train_score']),'+-',np.std(clf['train_score']))
print('mean test set accuracy:',np.mean(clf['test_score']),'+-',np.std(clf['test_score']))

mean train set accuracy: 0.9679659312710711 +- 0.003649325403713798
mean test set accuracy: 0.9497784810126582 +- 0.013608919570498668


# Repeated K-FOLD

In [16]:
#Logistics Regression
logit=LogisticRegression(penalty='l2',C=1,solver='liblinear',random_state=4,max_iter=10000)
#Repeated K-Fold crossvalidation
rkf=RepeatedKFold(n_splits=5,n_repeats=10,random_state=4)
print("We except k*n performance metrics:",5*10)
#search
clf=cross_validate(logit,x_train,y_train,scoring='accuracy',return_train_score=True,cv=rkf)
print('Number of metrics obtained:',len(clf['test_score']))
clf['test_score']

We except k*n performance metrics: 50
Number of metrics obtained: 50


array([0.9       , 0.9375    , 0.975     , 0.96202532, 0.94936709,
       0.9625    , 0.9625    , 0.9125    , 0.96202532, 0.92405063,
       0.9875    , 0.95      , 0.975     , 0.91139241, 0.96202532,
       0.95      , 0.9375    , 0.95      , 0.92405063, 0.96202532,
       0.975     , 0.9125    , 0.9375    , 0.94936709, 0.96202532,
       0.9875    , 0.9125    , 0.9375    , 0.91139241, 0.96202532,
       0.9625    , 0.9375    , 0.95      , 0.92405063, 0.93670886,
       0.95      , 0.95      , 0.95      , 0.98734177, 0.88607595,
       0.95      , 0.925     , 0.9625    , 0.96202532, 0.94936709,
       0.925     , 0.9625    , 0.925     , 0.91139241, 0.96202532])

In [17]:
print("Mean train test accuracy:",np.mean(clf['train_score']),'+-',np.std(clf['train_score']))
print("Mean test set accuracy:",np.mean(clf['test_score']),'+-',np.std(clf['test_score']))

Mean train test accuracy: 0.9603627688728534 +- 0.006592970819977563
Mean test set accuracy: 0.9454651898734177 +- 0.023290636388696693


# Leave one out

In [18]:
#Logistics regression
logit=LogisticRegression(penalty='l2',C=1,solver='liblinear',random_state=4,max_iter=10000)
loo=LeaveOneOut()

print("As we except many metrics as data in the train set:",len(x_train))

clf=cross_validate(logit,x_train,y_train,scoring='accuracy',return_train_score=True,cv=loo)
print("Number of metrics obtained:",len(clf['test_score']))
clf['test_score']

As we except many metrics as data in the train set: 398
Number of metrics obtained: 398


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [25]:
print('Mean train test accuracy:',np.mean(clf['train_score']),'+-',np.std(clf['train_score']))


Mean train test accuracy: 0.9575079427363519 +- 0.0012575839695838692


In [26]:
print("Mean test set accuracy:",np.mean(clf['test_score']),'+-',np.std(clf['test_score']))

Mean test set accuracy: 0.9472361809045227 +- 0.22356162123660028


# Leave P out

In [27]:
#Logistics Regression
logit=LogisticRegression(penalty='l2',solver='liblinear',random_state=4,max_iter=10000)
#Leave p out cross validation
lpo=LeavePOut(p=2)
#I take a smaller sample of data otherwise my computers runb out of memory
x_train_small=x_train.head(100)
y_train_small=y_train.head(100)
#The number of combination of N things tajken k at a time
print("We except:",comb(100,2),'metrics')
#Search
clf=cross_validate(logit,x_train_small,y_train_small,scoring='accuracy',return_train_score=True,cv=lpo)
print("Number of metrics obtained:",len(clf['test_score']))

We except: 4950.0 metrics
Number of metrics obtained: 4950


In [28]:
print("Mean train test accuracy:",np.mean(clf['train_score']),'+-',np.std(clf['train_score']))
print("Mean test set accuracy:",np.mean(clf['test_score']),'+-',np.std(clf['test_score']))

Mean train test accuracy: 0.9700020614306328 +- 0.0032367717044687024
Mean test set accuracy: 0.9190909090909091 +- 0.19298082235326716


# Stratified cross validation

In [31]:
#Logistics Regression
logit=LogisticRegression(penalty='l2',solver='liblinear',random_state=4,max_iter=10000)

#Staratified validation
sv=StratifiedKFold(n_splits=5,shuffle=True,random_state=4)
#Search
clf=cross_validate(logit,x_train,y_train,scoring='accuracy',return_train_score=True,cv=sv)
len(clf['test_score'])

5

In [ ]:
print("Mean train test accuracy:",np.mean())